name: Push
on:
  push:
    branches-ignore:
      - main
  workflow_call:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: '1.3.2'
      - name: Install dependencies
        run: poetry install
      - name: Run black
        run: poetry run black .
      - name: Run isort
        run: poetry run isort . --profile black
      - name: Commit style changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "fix: style fixes"
      - name: Check black
        run: poetry run black . --check
      - name: Check isort
        run: poetry run isort . --check-only --profile black
      - name: Check flake8
        run: poetry run flake8 . --max-line-length 120
      - name: Run tests
        run: poetry run pytest --cov=./ --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
