name: Release
on:
  push:
    branches: [ main ]

jobs:
  tests:
    name: "Run tests"
    uses: ./.github/workflows/push.yml
    secrets: inherit

  release:
    needs: tests
    name: "Release"
    runs-on: ubuntu-20.04
    permissions: write-all
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - run: npm install @semantic-release/exec@6.0.3 -D
      - name: Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 18.0.0
          extra_plugins: |
            @semantic-release/changelog@6.0.0
            @semantic-release/exec@6.0.3
            @semantic-release/git@10.0.0
            conventional-changelog-conventionalcommits@4.6.3

  publish-pypi:
    needs: release
    name: "Release to PYPI"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: '1.3.2'
      - name: Publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry config pypi-token.pypi $PYPI_TOKEN
          poetry publish --build
